name: Hello World!

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Current time
        run: |
          date
      - name: List long
        run: |
          ls -l
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: get commit
        if: ${{ github.event_name == 'pull_request' }}
        env:
          LAST_COMMIT: ${{ github.pull_request.head.sha }}
        run: echo "$LAST_COMMIT"
      - name: check functions
        if: ${{ contains(join(github.event.commits.*.message),'#skip') }}
        run: echo "check passed for contains and join"
